<?php
/**
 * @file
 * Install, update and uninstall functions for the password_policy_test module.
 *
 */


/**
 * Migrate password_policy_test variables to config.
 */
function password_policy_test_update_1000() {
  $config = config('password_policy_test.settings');
  $config->set('password_policy_test_force_change_allowed_paths_alter', update_variable_get('password_policy_test_force_change_allowed_paths_alter', array()));
  $config->save();

  update_variable_del('password_policy_test_force_change_allowed_paths_alter');
}

/**
 * Implements hook_install().
 */
function password_policy_test_install() {
  // Dynamically generated variable data was detected.
}
