<?php

/**
 * @file
 * Support module for testing Password Policy.
 *
 * Allows testing hooks as might be implemented by another module.
 */

/**
 * Implements hook_help().
 *
 * Dummy implementation to satisfy PAReview.
 */
function password_policy_test_help($path, $arg) {
  return '';
}

/**
 * Implements hook_password_policy_force_change_allowed_paths_alter().
 */
function password_policy_test_password_policy_force_change_allowed_paths_alter(&$allowed_paths) {
  if (_password_policy_test_is_testing_allowed_paths_alter()) {
    $allowed_paths[] = 'node';
    $allowed_paths[] = 'node/add/*';
  }
}

/**
 * Implements hook_config_info().
 */
function password_policy_test_config_info() {
  $prefixes['password_policy_test.settings'] = array(
    'label' => t('Password policy settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Determines whether the allowed paths alter feature is currently under test.
 */
function _password_policy_test_is_testing_allowed_paths_alter() {
  return config_get('password_policy_test.settings', 'password_policy_test_force_change_allowed_paths_alter');
}
